config/routes.rb
Rails.application.routes.draw do
  get "pages/dashboard"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "properties#index"
  resources :properties
  resources :tenants do
    resources :leases, only: [ :new, :create, :show ]
  end
  get "dashboard", to: "pages#dashboard"

  namespace :super_admin do
    resources :landlords, only: [ :index, :show, :update, :destroy ] do
      member do
        patch :approve
        delete :reject
      end
    end
    root to: "dashboard#index"
  end

  namespace :landlord do
    resources :properties do
      resources :leases do
        resources :payments, only: [ :index, :show, :new, :create ]
      end
    end
    root to: "dashboard#index"
  end

    resources :tenant do
      resources :dashboard, only: [ :index, :show ]
      resources :leases, only: [ :index, :show ] do
        resources :payments, only: [ :index, :show ]
      end
      root to: "dashboard#index"
    end
end

app/views/pages/dashboard.html.erb
<h1>Dashboard</h1>
<p> Welcome <%= @current_user.email%></p>
<p>Create <%= link_to 'New Property', new_property_path %></p>
<p>View <%= link_to 'My Tenants', tenants_path %></p>

<% if @properties.empty? == false %>
    <h3 style="margin-bottom: 40px;">Manage My Properties</h3>
    <table class="table table-bordered table-hover table-responsive">
                <thead class="thead-dark">
                    <tr class="table-active">
                        <!-- <th></th> -->
                        <th>Name</th>
                        <th>Address</th>
                        <th>Rent</th>
                        <th> # </th>
                    </tr>
                    </thead>
        <% @properties.each do |property| %>
            <tr>
                    <td class="bg-white"> <%= property.name %>  </th>
                    <td class="bg-white">   <%= property.address %> </td>
                    <td class="bg-white"> ZK<%= property.rent %> </td>
                    <td class="bg-white"> <%= link_to "View", property_path(property) %> </td>
            </tr>
            <% end %>
    </table>
<% end %>    